# Copyright 2023 The MathWorks, Inc.

name: "🐞 Report a Bug"
title: "[BUG]: (A short description of the bug...)"
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        #### Note:
        Before reporting a bug, see Issues to check if an issue already exists for the bug you encountered. To request a feature or report a vulnerability, return to [Create an Issue](https://github.com/chimmy-changa/issue-templates/issues).

  - type: markdown
    attributes:
      value: |
        ##  Provide details about the bug: 
        * What is the problem?
        * What behavior were you expecting? 
        * What happened instead? 
        * Include full errors, uncaught exceptions, stack traces, and relevant logs. 
        * Provide a sequence of steps to reproduce the issue. - Suggest a fix, if possible.
        
  - type: textarea
    id: bug-summary
    attributes:
      label: Summary of bug


      
  - type: input
    id: package-version
    attributes:
      label: Package version used



  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox        
        - Safari
        - Microsoft Edge

  - type: dropdown
    id: operating-system
    attributes:
      label: Which operating system was the matlab-proxy executable launched from?
      options:
        - Linux
        - Windows
        - Windows Subsystem for Linux (WSL)
        - MacOS (Intel)
        - MacOS (Apple Silicon)


  - type: textarea
    id: additional-context
    attributes:
      label: (Optional) Additional Information/Context 
      description: |
        Provide any other information that might be relevant for troubleshooting this bug. Context helps us develop a solution that is most useful in the real world.

  - type: markdown
    attributes:
      value: |
        ## Provide the output of the following commands 
        
  - type: markdown
    attributes:
      value: |
        ```
        pip freeze | grep -E "jupyter|matlab-proxy|jupyter-matlab-proxy"
        ```
        
  - type: textarea
    id: command-output-pip-freeze
    attributes:
      label: Command-output
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ```
        jupyter serverextension list
        ```
        
  - type: textarea
    id: command-output-jupyter-server-extension
    attributes:
      label: Command-output
    validations:
      required: true
