# Copyright 2023 The MathWorks, Inc.

name: "🐞 Bug Report"
title: "[BUG]: (A short description of the bug...)"
description: "Report a bug"
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        #### Note:
        Before reporting a bug, see [Issues](https://github.com/mathworks/matlab-proxy/issues) to check if an issue already exists for the bug you encountered. To request a feature or report a vulnerability, return to [Create an Issue](https://github.com/mathworks/matlab-proxy/issues/new/choose).

  - type: markdown
    attributes:
      value: |
        ##  Provide details about the bug: 
        * What is the problem?
        * What behavior were you expecting? 
        * What happened instead? 
        * Include full errors, uncaught exceptions, stack traces, and relevant logs. 
        * Provide a sequence of steps to reproduce the issue. - Suggest a fix, if possible.
        
  - type: textarea
    id: bug-summary
    attributes:
      label: Summary of bug
      
  - type: input
    id: package-version
    attributes:
      label: Package version used

  - type: dropdown
    id: browsers
    attributes:
      label: Browser(s) used
      multiple: true
      options:
        - Chrome
        - Firefox        
        - Safari
        - Microsoft Edge

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System used to start the matlab-proxy executable
      description: Provide any other information that might be relevant for troubleshooting this bug. Context helps us develop a solution that is most useful in the real world.
      options:
        - Linux
        - Windows
        - Windows Subsystem for Linux (WSL)
        - MacOS (Intel)
        - MacOS (Apple Silicon)        

  - type: textarea
    id: additional-context
    attributes:
      label: (Optional) Additional Information/Context 
      description: |
        Provide any other information that might be relevant for troubleshooting this bug. Context helps us develop a solution that is most useful in the real world.

  - type: markdown
    attributes:
      value: |
        ## Run the `troubleshooting.py` script and paste the output below.         
        
        ```bash
        $ python ./troubleshooting/troubleshooting.py
        ```

        If logging is enabled for `matlab-proxy` using the `MWI_LOG_FILE` environment variable, we recommend
        that you also enable it when executing the troubleshooting script:
         ```bash
        $ MWI_LOG_FILE="/tmp/log.file" python ./troubleshooting/troubleshooting.py
        ```
        For more information, check the [troubleshooting guide](https://github.com/mathworks/matlab-proxy/tree/main/troubleshooting)
        

  - type: textarea
    id: troubleshooting-script-output
    attributes:
      label: Script output
