blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://in.mathworks.com/support/contact_us.html
    about: Please report security vulnerabilities here.



