# Copyright 2023 The MathWorks, Inc.

blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/mathworks/matlab-proxy/security#reporting-security-vulnerabilities
    about: Please follow the steps mentioned here
